import type { Metadata } from "next";
//import { Playpen_Sans } from "next/font/google";
import "./globals.css";
/*
const playpenSans = Playpen_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});**/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}